import { Event } from "../../../types";

// Sample mock data
const mockEvents: Event[] = [
  {
    id: "1",
    title: "Tech Conference 2023",
    description: "A conference about emerging tech trends.",
    event_date: "2023-04-20",
    location: "Montreal",
    status: "active",
  },
  {
    id: "2",
    title: "Art Workshop",
    description: "A creative art workshop for beginners.",
    event_date: "2023-05-05",
    location: "Toronto",
    status: "cancelled",
  },
  {
    id: "3",
    title: "Science Expo",
    description: "Showcasing breakthrough scientific discoveries.",
    event_date: "2023-06-15",
    location: "Vancouver",
    status: "active",
  },
  {
    id: "4",
    title: "Business Seminar",
    description: "Strategies for modern business growth.",
    event_date: "2023-07-10",
    location: "Montreal",
    status: "postponed",
  },
  {
    id: "1",
    title: "Tech Conference 2023",
    description: "A conference about emerging tech trends.",
    event_date: "2023-04-20",
    location: "Montreal",
    status: "active",
  },
  {
    id: "2",
    title: "Art Workshop",
    description: "A creative art workshop for beginners.",
    event_date: "2023-05-05",
    location: "Toronto",
    status: "cancelled",
  },
  {
    id: "3",
    title: "Science Expo",
    description: "Showcasing breakthrough scientific discoveries.",
    event_date: "2023-06-15",
    location: "Vancouver",
    status: "active",
  },
  {
    id: "4",
    title: "Business Seminar",
    description: "Strategies for modern business growth.",
    event_date: "2023-07-10",
    location: "Montreal",
    status: "postponed",
  },
  {
    id: "1",
    title: "Tech Conference 2023",
    description: "A conference about emerging tech trends.",
    event_date: "2023-04-20",
    location: "Montreal",
    status: "active",
  },
  {
    id: "2",
    title: "Art Workshop",
    description: "A creative art workshop for beginners.",
    event_date: "2023-05-05",
    location: "Toronto",
    status: "cancelled",
  },
  {
    id: "3",
    title: "Science Expo",
    description: "Showcasing breakthrough scientific discoveries.",
    event_date: "2023-06-15",
    location: "Vancouver",
    status: "active",
  },
  {
    id: "4",
    title: "Business Seminar",
    description: "Strategies for modern business growth.",
    event_date: "2023-07-10",
    location: "Montreal",
    status: "postponed",
  },
  {
    id: "1",
    title: "Tech Conference 2023",
    description: "A conference about emerging tech trends.",
    event_date: "2023-04-20",
    location: "Montreal",
    status: "active",
  },
  {
    id: "2",
    title: "Art Workshop",
    description: "A creative art workshop for beginners.",
    event_date: "2023-05-05",
    location: "Toronto",
    status: "cancelled",
  },
  {
    id: "3",
    title: "Science Expo",
    description: "Showcasing breakthrough scientific discoveries.",
    event_date: "2023-06-15",
    location: "Vancouver",
    status: "active",
  },
  {
    id: "4",
    title: "Business Seminar",
    description: "Strategies for modern business growth.",
    event_date: "2023-07-10",
    location: "Montreal",
    status: "postponed",
  },
];

export { mockEvents };
